language: csharp
solution: LearningTravisCi.sln
 
script:
  - xbuild /p:Configuration=Debug solution-name.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore LearningTravisCi.sln
after_script:
  - nunit-console Tests/bin/Debug/Tests.dll
