language: csharp
solution: LearningTravisCi.sln

before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore LearningTravisCi.sln
after_script:
  - nunit-console Tests/bin/Debug/Tests.dll
